import { Injectable, signal, computed, inject } from '@angular/core';
import { GeminiService } from './gemini.service';

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private geminiService = inject(GeminiService);
  private readonly translationCache = signal<Record<string, string>>({});

  readonly currentLanguage = signal('en');
  readonly availableLanguages = [
    { code: 'en', name: 'English' },
    { code: 'ta', name: 'தமிழ்' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'es', name: 'Español' },
    { code: 'fr', name: 'Français' },
    { code: 'zh', name: '中国人' },
    { code: 'pt', name: 'Português' }
  ];

  private translations: Record<string, Record<string, string>> = {
    en: {
      title: 'AI Healthcare Assistant',
      placeholder: 'Type your health question...',
      speechNotSupported: 'Speech recognition is not supported by your browser.',
      speechErrorNoSpeech: "I didn't hear that. Please try speaking again.",
      speechErrorNotAllowed: "Microphone access denied. Please allow permissions in your browser settings.",
      speechErrorNetwork: "A network error occurred with speech recognition. Please check your connection.",
      speechErrorGeneric: "A speech recognition error occurred. Please try again.",
      history: 'History',
      newChat: 'New Chat',
      clearAll: 'Clear All',
      aiChat: 'AI Chat',
      medications: 'Medications',
      emergency: 'Emergency',
      records: 'Records',
      upcoming: 'Upcoming',
      mriScanning: 'MRI Scanning Analysis',
      onlineMedicineOrdering: 'Online Medicine Ordering',
      medicalReportScanning: 'Medical Report Scanning',
      comingSoon: 'Coming Soon',
      myMedications: 'My Medications',
      noMedicationsAdded: 'No Medications Added',
      addFirstMedication: "Click the '+' button to add your first medication reminder.",
      addMedication: 'Add Medication',
      medicationName: 'Medication Name',
      dosageExample: 'Dosage (e.g., 500mg, 1 tablet)',
      frequencyExample: 'Frequency (e.g., Twice a day)',
      numTablets: 'Number of Tablets',
      time: 'Time',
      cancel: 'Cancel',
      save: 'Save',
      emergencyAssistance: 'Emergency Assistance',
      emergencyInfo: 'Quick access to emergency services and contacts',
      ambulance: 'Ambulance',
      police: 'Police',
      myEmergencyContacts: 'My Emergency Contacts',
      addContact: '+ Add Contact',
      settings: 'Settings',
      appearance: 'Appearance',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      notifications: 'Notifications',
      whatsappNumber: 'WhatsApp Number',
      whatsappNumberPlaceholder: 'Enter number with country code',
      whatsappReminderMessage: 'Reminder to take your medication:',
      medicationReminder: 'Medication Reminder',
      timeToTakeMedication: "It's time to take your medication.",
      iveTakenIt: "I've Taken It",
      dismiss: 'Dismiss / Snooze',
      medicalRecords: 'Medical Records',
      selectFolderPrompt: 'Select a folder to view documents or create a new one.',
      createFolder: 'Create Folder',
      uploadDocument: 'Upload Document',
      documents: 'documents',
      noFolders: 'No Folders Found',
      createFirstFolder: 'Click "Create Folder" to get started.',
      rename: 'Rename',
      delete: 'Delete',
      uploadToFolder: 'Upload to Folder',
      noDocuments: 'No Documents in this Folder',
      uploadFirstDocument: 'Click "Upload to Folder" to add your first document.',
      folderNamePlaceholder: 'e.g., Blood Tests',
      create: 'Create',
      selectFolder: 'Select a Folder',
      chooseFolder: 'Choose a folder...',
      selectFile: 'Select a File',
      upload: 'Upload',
      areYouSure: 'Are you sure?',
      confirmDelete: 'This will permanently delete',
      folderDeleteWarning: 'All documents inside this folder will also be deleted.',
      previewNotAvailable: 'Preview not available for this file type.',
      emergencyCall: 'Emergency Call',
      call108: 'Call 108 - National Emergency Number',
      callAmbulanceLocation: 'Call Ambulance + Location',
      call108shareLocation: 'Call 108 and share your location automatically',
      nearbyHospitals: 'Nearby Hospitals',
      findHospitals: 'Find hospitals and clinics nearby',
      nearbyPharmacy: 'Nearby Pharmacy',
      findPharmacies: 'Find pharmacies near your location',
      share: 'Share',
      shareLocation: 'Share Location',
      shareGps: 'Share GPS location with emergency services',
      alertAllContacts: 'Alert All Contacts',
      sendSmsToContacts: 'Send emergency SMS to all contacts',
      videoCallDoctor: 'Video Call Doctor',
      startVideoConsult: 'Start emergency video consultation',
      doctorDirectory: 'Doctor Directory',
      contactDoctors: 'Contact available doctors directly',
      urgent: 'URGENT',
      open: 'OPEN',
      shareLocationPrompt: "Share your location using an option below, or copy the link.",
      copy: 'Copy',
      copied: 'Copied',
      close: 'Close',
      shareFile: 'Share File',
      shareFileNotSupported: 'Your browser does not support sharing files directly. Please download the document to share it manually.',
      downloadFile: 'Download File',
      profile: 'Profile',
      searchDoctors: 'Search doctors, hospitals...',
      call: 'Call',
      connecting: 'Connecting...',
      endCall: 'End Call',
    },
    ta: {
      title: 'AI சுகாதார உதவியாளர்',
      placeholder: 'உங்கள் சுகாதாரக் கேள்வியை தட்டச்சு செய்யவும்...',
      speechNotSupported: 'உங்கள் உலாவியில் பேச்சு அங்கீகாரம் ஆதரிக்கப்படவில்லை.',
      speechErrorNoSpeech: "எனக்கு எதுவும் கேட்கவில்லை. மீண்டும் பேச முயற்சிக்கவும்.",
      speechErrorNotAllowed: "மைக்ரோஃபோன் அணுகல் மறுக்கப்பட்டது. உங்கள் உலாவி அமைப்புகளில் அனுமதிகளை வழங்கவும்.",
      speechErrorNetwork: "பேச்சு அங்கீகாரத்தில் பிணையப் பிழை ஏற்பட்டது. உங்கள் இணைப்பைச் சரிபார்க்கவும்.",
      speechErrorGeneric: "பேச்சு அங்கீகாரத்தில் ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
      history: 'வரலாறு',
      newChat: 'புதிய அரட்டை',
      clearAll: 'அனைத்தையும் அழி',
      aiChat: 'AI அரட்டை',
      medications: 'மருந்துகள்',
      emergency: 'அவசரம்',
      records: 'பதிவுகள்',
      upcoming: 'வரவிருக்கும்',
      mriScanning: 'எம்ஆர்ஐ ஸ்கேன் பகுப்பாய்வு',
      onlineMedicineOrdering: 'ஆன்லைன் மருந்து ஆர்டர்',
      medicalReportScanning: 'மருத்துவ அறிக்கை ஸ்கேனிங்',
      comingSoon: 'விரைவில் வருகிறது',
      myMedications: 'என் மருந்துகள்',
      noMedicationsAdded: 'மருந்துகள் எதுவும் சேர்க்கப்படவில்லை',
      addFirstMedication: "உங்கள் முதல் மருந்து நினைவூட்டலைச் சேர்க்க '+' பொத்தானைக் கிளிக் செய்யவும்.",
      addMedication: ' மருந்து சேர்க்கவும்',
      medicationName: 'மருந்தின் பெயர்',
      dosageExample: 'மருந்தளவு (எ.கா., 500mg, 1 மாத்திரை)',
      frequencyExample: 'அடிக்கடி (எ.கா., ஒரு நாளைக்கு இரண்டு முறை)',
      numTablets: 'மாத்திரைகளின் எண்ணிக்கை',
      time: 'நேரம்',
      cancel: 'ரத்துசெய்',
      save: 'சேமி',
      emergencyAssistance: 'அவசர உதவி',
      emergencyInfo: 'அவசர சேவைகள் மற்றும் தொடர்புகளுக்கான விரைவான அணுகல்',
      ambulance: 'ஆம்புலன்ஸ்',
      police: 'காவல்துறை',
      myEmergencyContacts: 'எனது அவசர தொடர்புகள்',
      addContact: '+ தொடர்பைச் சேர்க்கவும்',
      settings: 'அமைப்புகள்',
      appearance: 'தோற்றம்',
      theme: 'தீம்',
      light: 'ஒளி',
      dark: 'இருள்',
      notifications: 'அறிவிப்புகள்',
      whatsappNumber: 'வாட்ஸ்அப் எண்',
      whatsappNumberPlaceholder: 'நாட்டு குறியீட்டுடன் எண்ணை உள்ளிடவும்',
      whatsappReminderMessage: 'உங்கள் மருந்தை எடுத்துக்கொள்ள நினைவூட்டல்:',
      medicationReminder: 'மருந்து நினைவூட்டல்',
      timeToTakeMedication: 'உங்கள் மருந்தை எடுத்துக்கொள்ள வேண்டிய நேரம் இது.',
      iveTakenIt: 'நான் எடுத்துக்கொண்டேன்',
      dismiss: 'தள்ளுபடி / உறக்கநிலை',
      medicalRecords: 'மருத்துவ பதிவுகள்',
      selectFolderPrompt: 'ஆவணங்களைக் காண ஒரு கோப்புறையைத் தேர்ந்தெடுக்கவும் அல்லது புதிய ஒன்றை உருவாக்கவும்.',
      createFolder: 'கோப்புறையை உருவாக்கு',
      uploadDocument: 'ஆவணத்தைப் பதிவேற்று',
      documents: 'ஆவணங்கள்',
      noFolders: 'கோப்புறைகள் எதுவும் இல்லை',
      createFirstFolder: 'தொடங்குவதற்கு "கோப்புறையை உருவாக்கு" என்பதைக் கிளிக் செய்யவும்.',
      rename: 'பெயர் மாற்று',
      delete: 'அழி',
      uploadToFolder: 'கோப்புறையில் பதிவேற்று',
      noDocuments: 'இந்த கோப்புறையில் ஆவணங்கள் இல்லை',
      uploadFirstDocument: 'உங்கள் முதல் ஆவணத்தைச் சேர்க்க "கோப்புறையில் பதிவேற்று" என்பதைக் கிளிக் செய்யவும்.',
      folderNamePlaceholder: 'எ.கா., இரத்தப் பரிசோதனைகள்',
      create: 'உருவாக்கு',
      selectFolder: 'ஒரு கோப்புறையைத் தேர்ந்தெடுக்கவும்',
      chooseFolder: 'ஒரு கோப்புறையைத் தேர்வுசெய்க...',
      selectFile: 'ஒரு கோப்பைத் தேர்ந்தெடுக்கவும்',
      upload: 'பதிவேற்று',
      areYouSure: 'உறுதியாகவா?',
      confirmDelete: 'இது நிரந்தரமாக நீக்கப்படும்',
      folderDeleteWarning: 'இந்த கோப்புறையில் உள்ள அனைத்து ஆவணங்களும் நீக்கப்படும்.',
      previewNotAvailable: 'இந்த கோப்பு வகைக்கு முன்னோட்டம் இல்லை.',
      emergencyCall: 'அவசர அழைப்பு',
      call108: '108 ஐ அழைக்கவும் - தேசிய அவசர எண்',
      callAmbulanceLocation: 'ஆம்புலன்ஸ் + இருப்பிடத்தை அழைக்கவும்',
      call108shareLocation: '108 ஐ அழைத்து உங்கள் இருப்பிடத்தைத் தானாகப் பகிரவும்',
      nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
      findHospitals: 'அருகிலுள்ள மருத்துவமனைகள் மற்றும் கிளினிக்குகளைக் கண்டறியவும்',
      nearbyPharmacy: 'அருகிலுள்ள மருந்தகம்',
      findPharmacies: 'உங்கள் இருப்பிடத்திற்கு அருகிலுள்ள மருந்தகங்களைக் கண்டறியவும்',
      share: 'பகிர்',
      shareLocation: 'இருப்பிடத்தைப் பகிரவும்',
      shareGps: 'அவசர சேவைகளுடன் ஜிபிஎஸ் இருப்பிடத்தைப் பகிரவும்',
      alertAllContacts: 'அனைத்து தொடர்புகளையும் எச்சரிக்கவும்',
      sendSmsToContacts: 'அனைத்து தொடர்புகளுக்கும் அவசர எஸ்எம்எஸ் அனுப்பவும்',
      videoCallDoctor: 'மருத்துவருடன் வீடியோ அழைப்பு',
      startVideoConsult: 'அவசர வீடியோ ஆலோசனையைத் தொடங்கவும்',
      doctorDirectory: 'மருத்துவர் அடைவு',
      contactDoctors: 'கிடைக்கக்கூடிய மருத்துவர்களை நேரடியாகத் தொடர்பு கொள்ளவும்',
      urgent: 'அவசரம்',
      open: 'திற',
      shareLocationPrompt: 'கீழே உள்ள விருப்பங்களில் ஒன்றைப் பயன்படுத்தி உங்கள் இருப்பிடத்தைப் பகிரவும் அல்லது இணைப்பை நகலெடுக்கவும்.',
      copy: 'நகலெடு',
      copied: 'நகலெடுக்கப்பட்டது',
      close: 'மூடு',
      shareFile: 'கோப்பைப் பகிரவும்',
      shareFileNotSupported: 'உங்கள் உலாவி நேரடியாக கோப்புகளைப் பகிர்வதை ஆதரிக்கவில்லை. ஆவணத்தை கைமுறையாகப் பகிர, பதிவிறக்கவும்.',
      downloadFile: 'கோப்பைப் பதிவிறக்கவும்',
      profile: 'சுயவிவரம்',
      searchDoctors: 'மருத்துவர்கள், மருத்துவமனைகள் தேடு...',
      call: 'அழை',
      connecting: 'இணைக்கப்படுகிறது...',
      endCall: 'அழைப்பை ముగించు',
    },
    hi: {
      title: 'एआई हेल्थकेयर असिस्टेंट',
      placeholder: 'अपना स्वास्थ्य प्रश्न टाइप करें...',
      speechNotSupported: 'आपके ब्राउज़र द्वारा वाक् पहचान समर्थित नहीं है।',
      speechErrorNoSpeech: "मैंने वह नहीं सुना। कृपया फिर से बोलने का प्रयास करें।",
      speechErrorNotAllowed: "माइक्रोफ़ोन का उपयोग अस्वीकृत। कृपया अपनी ब्राउज़र सेटिंग्स में अनुमति दें।",
      speechErrorNetwork: "वाक् पहचान में नेटवर्क त्रुटि हुई। कृपया अपना कनेक्शन जांचें।",
      speechErrorGeneric: "वाक् पहचान में एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
      history: 'इतिहास',
      newChat: 'नई चैट',
      clearAll: 'सब साफ़ करो',
      aiChat: 'एआई चैट',
      medications: 'दवाएं',
      emergency: 'आपातकालीन',
      records: 'अभिलेख',
      upcoming: 'आगामी',
      mriScanning: 'एमआरआई स्कैन विश्लेषण',
      onlineMedicineOrdering: 'ऑनलाइन दवा ऑर्डरिंग',
      medicalReportScanning: 'मेडिकल रिपोर्ट स्कैनिंग',
      comingSoon: 'जल्द आ रहा है',
      myMedications: 'मेरी दवाएं',
      noMedicationsAdded: 'कोई दवा नहीं जोड़ी गई',
      addFirstMedication: "अपना पहला दवा अनुस्मारक जोड़ने के लिए '+' बटन पर क्लिक करें।",
      addMedication: 'दवा जोड़ें',
      medicationName: 'दवा का नाम',
      dosageExample: 'खुराक (जैसे, 500mg, 1 टैबलेट)',
      frequencyExample: 'आवृत्ति (जैसे, दिन में दो बार)',
      numTablets: 'गोलियों की संख्या',
      time: 'समय',
      cancel: 'रद्द करना',
      save: 'बचाना',
      emergencyAssistance: 'आपातकालीन सहायता',
      emergencyInfo: 'आपातकालीन सेवाओं और संपर्कों तक त्वरित पहुंच',
      ambulance: 'एम्बुलेंस',
      police: 'पुलिस',
      myEmergencyContacts: 'मेरे आपातकालीन संपर्क',
      addContact: '+ संपर्क जोड़ें',
      settings: 'समायोजन',
      appearance: 'दिखावट',
      theme: 'थीम',
      light: 'रोशनी',
      dark: 'अंधेरा',
      notifications: 'सूचनाएं',
      whatsappNumber: 'व्हाट्सएप नंबर',
      whatsappNumberPlaceholder: 'देश कोड के साथ नंबर दर्ज करें',
      whatsappReminderMessage: 'अपनी दवा लेने के लिए अनुस्मारक:',
      medicationReminder: 'दवा अनुस्मारक',
      timeToTakeMedication: 'यह आपकी दवा लेने का समय है।',
      iveTakenIt: 'मैंने ले ली है',
      dismiss: 'ख़ारिज करें / याद दिलाएं',
      medicalRecords: 'चिकित्सा अभिलेख',
      selectFolderPrompt: 'दस्तावेज़ देखने के लिए एक फ़ोल्डर चुनें या एक नया बनाएं।',
      createFolder: 'फ़ोल्डर बनाएं',
      uploadDocument: 'दस्तावेज़ अपलोड करें',
      documents: 'दस्तावेज़',
      noFolders: 'कोई फ़ोल्डर नहीं मिला',
      createFirstFolder: 'शुरू करने के लिए "फ़ोल्डर बनाएं" पर क्लिक करें।',
      rename: 'नाम बदलें',
      delete: 'हटाएं',
      uploadToFolder: 'फ़ोल्डर में अपलोड करें',
      noDocuments: 'इस फ़ोल्डर में कोई दस्तावेज़ नहीं है',
      uploadFirstDocument: 'अपना पहला दस्तावेज़ जोड़ने के लिए "फ़ोल्डर में अपलोड करें" पर क्लिक करें।',
      folderNamePlaceholder: 'जैसे, रक्त परीक्षण',
      create: 'बनाएं',
      selectFolder: 'एक फ़ोल्डर चुनें',
      chooseFolder: 'एक फ़ोल्डर चुनें...',
      selectFile: 'एक फ़ाइल चुनें',
      upload: 'अपलोड करें',
      areYouSure: 'क्या आप निश्चित हैं?',
      confirmDelete: 'यह स्थायी रूप से हटा देगा',
      folderDeleteWarning: 'इस फ़ोल्डर के अंदर के सभी दस्तावेज़ भी हटा दिए जाएंगे।',
      previewNotAvailable: 'इस फ़ाइल प्रकार के लिए पूर्वावलोकन उपलब्ध नहीं है।',
      emergencyCall: 'आपातकालीन कॉल',
      call108: '108 पर कॉल करें - राष्ट्रीय आपातकालीन नंबर',
      callAmbulanceLocation: 'एम्बुलेंस + स्थान पर कॉल करें',
      call108shareLocation: '108 पर कॉल करें और स्वचालित रूप से अपना स्थान साझा करें',
      nearbyHospitals: 'आस-पास के अस्पताल',
      findHospitals: 'आस-पास के अस्पताल और क्लीनिक खोजें',
      nearbyPharmacy: 'आस-पास की फार्मेसी',
      findPharmacies: 'अपने स्थान के पास फार्मेसियों का पता लगाएं',
      share: 'शेयर',
      shareLocation: 'स्थान साझा करें',
      shareGps: 'आपातकालीन सेवाओं के साथ जीपीएस स्थान साझा करें',
      alertAllContacts: 'सभी संपर्कों को सचेत करें',
      sendSmsToContacts: 'सभी संपर्कों को आपातकालीन एसएमएस भेजें',
      videoCallDoctor: 'डॉक्टर को वीडियो कॉल करें',
      startVideoConsult: 'आपातकालीन वीडियो परामर्श शुरू करें',
      doctorDirectory: 'डॉक्टर निर्देशिका',
      contactDoctors: 'उपलब्ध डॉक्टरों से सीधे संपर्क करें',
      urgent: 'अत्यावश्यक',
      open: 'खोलें',
      shareLocationPrompt: 'नीचे दिए गए विकल्पों में से किसी एक का उपयोग करके अपना स्थान साझा करें, या लिंक कॉपी करें।',
      copy: 'कॉपी करें',
      copied: 'कॉपी किया गया',
      close: 'बंद करें',
      shareFile: 'फ़ाइल साझा करें',
      shareFileNotSupported: 'आपका ब्राउज़र सीधे फ़ाइलें साझा करने का समर्थन नहीं करता है। दस्तावेज़ को मैन्युअल रूप से साझा करने के लिए कृपया इसे डाउनलोड करें।',
      downloadFile: 'फ़ाइल डाउनलोड करें',
      profile: 'प्रोफ़ाइल',
      searchDoctors: 'डॉक्टर, अस्पताल खोजें...',
      call: 'बुलाना',
      connecting: 'कनेक्ट हो रहा है...',
      endCall: 'कॉल समाप्त करें',
    },
    es: {
      title: 'Asistente de Salud IA',
      placeholder: 'Escriba su pregunta de salud...',
      speechNotSupported: 'El reconocimiento de voz no es compatible con su navegador.',
      speechErrorNoSpeech: 'No he oído nada. Por favor, intente hablar de nuevo.',
      speechErrorNotAllowed: 'Acceso al micrófono denegado. Por favor, permita los permisos en la configuración de su navegador.',
      speechErrorNetwork: 'Se ha producido un error de red con el reconocimiento de voz. Por favor, compruebe su conexión.',
      speechErrorGeneric: 'Se ha producido un error en el reconocimiento de voz. Por favor, inténtelo de nuevo.',
      history: 'Historial',
      newChat: 'Nuevo chat',
      clearAll: 'Limpiar todo',
      aiChat: 'Chat de IA',
      medications: 'Medicamentos',
      emergency: 'Emergencia',
      records: 'Registros',
      upcoming: 'Próximamente',
      mriScanning: 'Análisis de resonancia magnética',
      onlineMedicineOrdering: 'Pedido de medicamentos en línea',
      medicalReportScanning: 'Escaneo de informes médicos',
      comingSoon: 'Próximamente',
      myMedications: 'Mis Medicamentos',
      noMedicationsAdded: 'No se han añadido medicamentos',
      addFirstMedication: "Haga clic en el botón '+' para añadir su primer recordatorio de medicación.",
      addMedication: 'Añadir Medicamento',
      medicationName: 'Nombre del Medicamento',
      dosageExample: 'Dosis (p. ej., 500mg, 1 comprimido)',
      frequencyExample: 'Frecuencia (p. ej., dos veces al día)',
      numTablets: 'Número de Tabletas',
      time: 'Hora',
      cancel: 'Cancelar',
      save: 'Guardar',
      emergencyAssistance: 'Asistencia de Emergencia',
      emergencyInfo: 'Acceso rápido a servicios y contactos de emergencia',
      ambulance: 'Ambulancia',
      police: 'Policía',
      myEmergencyContacts: 'Mis Contactos de Emergencia',
      addContact: '+ Añadir Contacto',
      settings: 'Ajustes',
      appearance: 'Apariencia',
      theme: 'Tema',
      light: 'Claro',
      dark: 'Oscuro',
      notifications: 'Notificaciones',
      whatsappNumber: 'Número de WhatsApp',
      whatsappNumberPlaceholder: 'Introduzca el número con el código del país',
      whatsappReminderMessage: 'Recordatorio para tomar su medicamento:',
      medicationReminder: 'Recordatorio de Medicación',
      timeToTakeMedication: 'Es hora de tomar su medicación.',
      iveTakenIt: 'La he tomado',
      dismiss: 'Descartar / Posponer',
      medicalRecords: 'Registros Médicos',
      selectFolderPrompt: 'Seleccione una carpeta para ver documentos o cree una nueva.',
      createFolder: 'Crear carpeta',
      uploadDocument: 'Subir documento',
      documents: 'documentos',
      noFolders: 'No se encontraron carpetas',
      createFirstFolder: 'Haga clic en "Crear carpeta" para comenzar.',
      rename: 'Renombrar',
      delete: 'Eliminar',
      uploadToFolder: 'Subir a la carpeta',
      noDocuments: 'No hay documentos en esta carpeta',
      uploadFirstDocument: 'Haga clic en "Subir a la carpeta" para agregar su primer documento.',
      folderNamePlaceholder: 'p. ej., Análisis de sangre',
      create: 'Crear',
      selectFolder: 'Seleccionar una carpeta',
      chooseFolder: 'Elija una carpeta...',
      selectFile: 'Seleccionar un archivo',
      upload: 'Subir',
      areYouSure: '¿Estás seguro?',
      confirmDelete: 'Esto eliminará permanentemente',
      folderDeleteWarning: 'Todos los documentos dentro de esta carpeta también serán eliminados.',
      previewNotAvailable: 'La vista previa no está disponible para este tipo de archivo.',
      emergencyCall: 'Llamada de emergencia',
      call108: 'Llamar al 108 - Número Nacional de Emergencia',
      callAmbulanceLocation: 'Llamar Ambulancia + Ubicación',
      call108shareLocation: 'Llamar al 108 y compartir su ubicación automáticamente',
      nearbyHospitals: 'Hospitales cercanos',
      findHospitals: 'Encontrar hospitales y clínicas cercanas',
      nearbyPharmacy: 'Farmacia cercana',
      findPharmacies: 'Encontrar farmacias cerca de su ubicación',
      share: 'Compartir',
      shareLocation: 'Compartir ubicación',
      shareGps: 'Compartir ubicación GPS con servicios de emergencia',
      alertAllContacts: 'Alertar a todos los contactos',
      sendSmsToContacts: 'Enviar SMS de emergencia a todos los contactos',
      videoCallDoctor: 'Videollamada al Doctor',
      startVideoConsult: 'Iniciar videoconsulta de emergencia',
      doctorDirectory: 'Directorio de Médicos',
      contactDoctors: 'Contactar directamente a los médicos disponibles',
      urgent: 'URGENTE',
      open: 'ABRIR',
      shareLocationPrompt: 'Comparta su ubicación utilizando una de las siguientes opciones o copie el enlace.',
      copy: 'Copiar',
      copied: 'Copiado',
      close: 'Cerrar',
      shareFile: 'Compartir Archivo',
      shareFileNotSupported: 'Su navegador no permite compartir archivos directamente. Por favor, descargue el documento para compartirlo manualmente.',
      downloadFile: 'Descargar Archivo',
      profile: 'Perfil',
      searchDoctors: 'Buscar médicos, hospitales...',
      call: 'Llamar',
      connecting: 'Conectando...',
      endCall: 'Finalizar llamada',
    },
    fr: {
      title: 'Assistant de Santé IA',
      placeholder: 'Tapez votre question de santé...',
      speechNotSupported: 'La reconnaissance vocale n\'est pas prise en charge par votre navigateur.',
      speechErrorNoSpeech: 'Je n\'ai rien entendu. Veuillez réessayer de parler.',
      speechErrorNotAllowed: 'Accès au microphone refusé. Veuillez autoriser les permissions dans les paramètres de votre navigateur.',
      speechErrorNetwork: 'Une erreur de réseau s\'est produite avec la reconnaissance vocale. Veuillez vérifier votre connexion.',
      speechErrorGeneric: 'Une erreur de reconnaissance vocale s\'est produite. Veuillez réessayer.',
      history: 'Historique',
      newChat: 'Nouveau chat',
      clearAll: 'Tout effacer',
      aiChat: 'Chat IA',
      medications: 'Médicaments',
      emergency: 'Urgence',
      records: 'Dossiers',
      upcoming: 'À venir',
      mriScanning: 'Analyse d\'IRM',
      onlineMedicineOrdering: 'Commande de médicaments en ligne',
      medicalReportScanning: 'Numérisation de rapports médicaux',
      comingSoon: 'Bientôt disponible',
      myMedications: 'Mes Médicaments',
      noMedicationsAdded: 'Aucun médicament ajouté',
      addFirstMedication: "Cliquez sur le bouton '+' pour ajouter votre premier rappel de médicament.",
      addMedication: 'Ajouter un médicament',
      medicationName: 'Nom du médicament',
      dosageExample: 'Dosage (par ex., 500mg, 1 comprimé)',
      frequencyExample: 'Fréquence (par ex., deux fois par jour)',
      numTablets: 'Nombre de comprimés',
      time: 'Heure',
      cancel: 'Annuler',
      save: 'Enregistrer',
      emergencyAssistance: 'Assistance d\'urgence',
      emergencyInfo: 'Accès rapide aux services et contacts d\'urgence',
      ambulance: 'Ambulance',
      police: 'Police',
      myEmergencyContacts: 'Mes contacts d\'urgence',
      addContact: '+ Ajouter un contact',
      settings: 'Paramètres',
      appearance: 'Apparence',
      theme: 'Thème',
      light: 'Clair',
      dark: 'Sombre',
      notifications: 'Notifications',
      whatsappNumber: 'Numéro WhatsApp',
      whatsappNumberPlaceholder: 'Entrez le numéro avec l\'indicatif du pays',
      whatsappReminderMessage: 'Rappel pour prendre votre médicament :',
      medicationReminder: 'Rappel de médicament',
      timeToTakeMedication: 'Il est temps de prendre votre médicament.',
      iveTakenIt: 'Je l\'ai pris',
      dismiss: 'Rejeter / Répéter',
      medicalRecords: 'Dossiers Médicaux',
      selectFolderPrompt: 'Sélectionnez un dossier pour afficher des documents ou en créer un nouveau.',
      createFolder: 'Créer un dossier',
      uploadDocument: 'Télécharger un document',
      documents: 'documents',
      noFolders: 'Aucun dossier trouvé',
      createFirstFolder: 'Cliquez sur "Créer un dossier" pour commencer.',
      rename: 'Renommer',
      delete: 'Supprimer',
      uploadToFolder: 'Télécharger dans le dossier',
      noDocuments: 'Aucun document dans ce dossier',
      uploadFirstDocument: 'Cliquez sur "Télécharger dans le dossier" pour ajouter votre premier document.',
      folderNamePlaceholder: 'ex: Analyses de sang',
      create: 'Créer',
      selectFolder: 'Sélectionner un dossier',
      chooseFolder: 'Choisissez un dossier...',
      selectFile: 'Sélectionner un fichier',
      upload: 'Télécharger',
      areYouSure: 'Êtes-vous sûr(e)?',
      confirmDelete: 'Cela supprimera définitivement',
      folderDeleteWarning: 'Tous les documents de ce dossier seront également supprimés.',
      previewNotAvailable: 'L\'aperçu n\'est pas disponible pour ce type de fichier.',
      emergencyCall: 'Appel d\'urgence',
      call108: 'Appeler le 108 - Numéro national d\'urgence',
      callAmbulanceLocation: 'Appeler l\'ambulance + Localisation',
      call108shareLocation: 'Appeler le 108 et partager automatiquement votre position',
      nearbyHospitals: 'Hôpitaux à proximité',
      findHospitals: 'Trouver des hôpitaux et des cliniques à proximité',
      nearbyPharmacy: 'Pharmacie à proximité',
      findPharmacies: 'Trouver des pharmacies près de chez vous',
      share: 'Partager',
      shareLocation: 'Partager la localisation',
      shareGps: 'Partager la localisation GPS avec les services d\'urgence',
      alertAllContacts: 'Alerter tous les contacts',
      sendSmsToContacts: 'Envoyer un SMS d\'urgence à tous les contacts',
      videoCallDoctor: 'Appel vidéo avec un médecin',
      startVideoConsult: 'Démarrer une consultation vidéo d\'urgence',
      doctorDirectory: 'Annuaire des médecins',
      contactDoctors: 'Contacter directement les médecins disponibles',
      urgent: 'URGENT',
      open: 'OUVRIR',
      shareLocationPrompt: 'Partagez votre position en utilisant l\'une des options ci-dessous, ou copiez le lien.',
      copy: 'Copier',
      copied: 'Copié',
      close: 'Fermer',
      shareFile: 'Partager le Fichier',
      shareFileNotSupported: 'Votre navigateur ne prend pas en charge le partage de fichiers directement. Veuillez télécharger le document pour le partager manuellement.',
      downloadFile: 'Télécharger le Fichier',
      profile: 'Profil',
      searchDoctors: 'Rechercher des médecins, des hôpitaux...',
      call: 'Appeler',
      connecting: 'Connexion en cours...',
      endCall: 'Terminer l\'appel',
    },
    zh: {
      title: 'AI 健康助手',
      placeholder: '输入您的健康问题...',
      speechNotSupported: '您的浏览器不支持语音识别。',
      speechErrorNoSpeech: '我没听到。请再试一次。',
      speechErrorNotAllowed: '麦克风访问被拒绝。请在您的浏览器设置中允许权限。',
      speechErrorNetwork: '语音识别发生网络错误。请检查您的连接。',
      speechErrorGeneric: '发生语音识别错误。请再试一次。',
      history: '历史',
      newChat: '新聊天',
      clearAll: '全部清除',
      aiChat: 'AI聊天',
      medications: '药物',
      emergency: '紧急情况',
      records: '记录',
      upcoming: '即将推出',
      mriScanning: '核磁共振扫描分析',
      onlineMedicineOrdering: '在线药品订购',
      medicalReportScanning: '医疗报告扫描',
      comingSoon: '敬请期待',
      myMedications: '我的药物',
      noMedicationsAdded: '未添加药物',
      addFirstMedication: "点击“+”按钮添加您的第一个用药提醒。",
      addMedication: '添加药物',
      medicationName: '药物名称',
      dosageExample: '剂量（例如，500毫克，1片）',
      frequencyExample: '频率（例如，每天两次）',
      numTablets: '片剂数量',
      time: '时间',
      cancel: '取消',
      save: '保存',
      emergencyAssistance: '紧急援助',
      emergencyInfo: '快速访问紧急服务和联系人',
      ambulance: '救护车',
      police: '警察',
      myEmergencyContacts: '我的紧急联系人',
      addContact: '+ 添加联系人',
      settings: '设置',
      appearance: '外貌',
      theme: '主题',
      light: ' светлый',
      dark: '黑暗的',
      notifications: '通知',
      whatsappNumber: 'WhatsApp 号码',
      whatsappNumberPlaceholder: '输入带国家代码的号码',
      whatsappReminderMessage: '提醒您服药：',
      medicationReminder: '用药提醒',
      timeToTakeMedication: '该吃药了。',
      iveTakenIt: '我吃过了',
      dismiss: '忽略/稍后提醒',
      medicalRecords: '医疗记录',
      selectFolderPrompt: '选择一个文件夹查看文件或创建一个新的。',
      createFolder: '创建文件夹',
      uploadDocument: '上传文件',
      documents: '文件',
      noFolders: '未找到文件夹',
      createFirstFolder: '点击“创建文件夹”开始。',
      rename: '重命名',
      delete: '删除',
      uploadToFolder: '上传到文件夹',
      noDocuments: '此文件夹中没有文件',
      uploadFirstDocument: '点击“上传到文件夹”添加您的第一个文件。',
      folderNamePlaceholder: '例如，血液检查',
      create: '创建',
      selectFolder: '选择一个文件夹',
      chooseFolder: '选择一个文件夹...',
      selectFile: '选择一个文件',
      upload: '上传',
      areYouSure: '你确定吗？',
      confirmDelete: '这将永久删除',
      folderDeleteWarning: '此文件夹中的所有文件也将被删除。',
      previewNotAvailable: '此文件类型无法预览。',
      emergencyCall: '紧急呼叫',
      call108: '拨打108 - 国家紧急号码',
      callAmbulanceLocation: '呼叫救护车+位置',
      call108shareLocation: '拨打108并自动分享您的位置',
      nearbyHospitals: '附近的医院',
      findHospitals: '查找附近的医院和诊所',
      nearbyPharmacy: '附近的药房',
      findPharmacies: '查找您所在地附近的药房',
      share: '分享',
      shareLocation: '分享位置',
      shareGps: '与紧急服务共享GPS位置',
      alertAllContacts: '提醒所有联系人',
      sendSmsToContacts: '向所有联系人发送紧急短信',
      videoCallDoctor: '视频呼叫医生',
      startVideoConsult: '开始紧急视频咨询',
      doctorDirectory: '医生目录',
      contactDoctors: '直接联系可用医生',
      urgent: '紧急',
      open: '打开',
      shareLocationPrompt: '使用以下选项之一分享您的位置，或复制链接。',
      copy: '复制',
      copied: '已复制',
      close: '关闭',
      shareFile: '分享文件',
      shareFileNotSupported: '您的浏览器不支持直接分享文件。请下载文件后手动分享。',
      downloadFile: '下载文件',
      profile: '个人资料',
      searchDoctors: '搜索医生、医院...',
      call: '呼叫',
      connecting: '连接中...',
      endCall: '结束通话',
    },
    pt: {
      title: 'Assistente de Saúde IA',
      placeholder: 'Digite sua pergunta de saúde...',
      speechNotSupported: 'O reconhecimento de fala não é suportado pelo seu navegador.',
      speechErrorNoSpeech: 'Não ouvi nada. Por favor, tente falar novamente.',
      speechErrorNotAllowed: 'Acesso ao microfone negado. Por favor, permita as permissões nas configurações do seu navegador.',
      speechErrorNetwork: 'Ocorreu um erro de rede no reconhecimento de fala. Por favor, verifique sua conexão.',
      speechErrorGeneric: 'Ocorreu um erro no reconocimiento de fala. Por favor, tente novamente.',
      history: 'Histórico',
      newChat: 'Novo chat',
      clearAll: 'Limpar tudo',
      aiChat: 'Chat de IA',
      medications: 'Medicamentos',
      emergency: 'Emergência',
      records: 'Registros',
      upcoming: 'Em breve',
      mriScanning: 'Análise de ressonância magnética',
      onlineMedicineOrdering: 'Encomenda de medicamentos online',
      medicalReportScanning: 'Digitalização de relatórios médicos',
      comingSoon: 'Em breve',
      myMedications: 'Meus Medicamentos',
      noMedicationsAdded: 'Nenhum medicamento adicionado',
      addFirstMedication: "Clique no botão '+' para adicionar seu primeiro lembrete de medicação.",
      addMedication: 'Adicionar Medicamento',
      medicationName: 'Nome do Medicamento',
      dosageExample: 'Dosagem (ex: 500mg, 1 comprimido)',
      frequencyExample: 'Frequência (ex: duas vezes ao dia)',
      numTablets: 'Número de Comprimidos',
      time: 'Hora',
      cancel: 'Cancelar',
      save: 'Salvar',
      emergencyAssistance: 'Assistência de Emergência',
      emergencyInfo: 'Acesso rápido a serviços e contatos de emergência',
      ambulance: 'Ambulância',
      police: 'Polícia',
      myEmergencyContacts: 'Meus Contatos de Emergência',
      addContact: '+ Adicionar Contato',
      settings: 'Configurações',
      theme: 'Tema',
      light: 'Claro',
      dark: 'Escuro',
      notifications: 'Notificações',
      whatsappNumber: 'Número do WhatsApp',
      whatsappNumberPlaceholder: 'Digite o número com o código do país',
      whatsappReminderMessage: 'Lembrete para tomar seu medicamento:',
      medicationReminder: 'Lembrete de Medicação',
      timeToTakeMedication: 'É hora de tomar sua medicação.',
      iveTakenIt: 'Eu tomei',
      dismiss: 'Dispensar / Adiar',
      medicalRecords: 'Registros Médicos',
      selectFolderPrompt: 'Selecione uma pasta para ver documentos ou crie uma nova.',
      createFolder: 'Criar Pasta',
      uploadDocument: 'Carregar Documento',
      documents: 'documentos',
      noFolders: 'Nenhuma pasta encontrada',
      createFirstFolder: 'Clique em "Criar Pasta" para começar.',
      rename: 'Renomear',
      delete: 'Excluir',
      uploadToFolder: 'Carregar para a Pasta',
      noDocuments: 'Nenhum documento nesta pasta',
      uploadFirstDocument: 'Clique em "Carregar para a Pasta" para adicionar seu primeiro documento.',
      folderNamePlaceholder: 'ex: Exames de sangue',
      create: 'Criar',
      selectFolder: 'Selecione uma Pasta',
      chooseFolder: 'Escolha uma pasta...',
      selectFile: 'Selecione um arquivo',
      upload: 'Carregar',
      areYouSure: 'Você tem certeza?',
      confirmDelete: 'Isso excluirá permanentemente',
      folderDeleteWarning: 'Todos os documentos dentro desta pasta também serão excluídos.',
      previewNotAvailable: 'A visualização não está disponível para este tipo de arquivo.',
      emergencyCall: 'Chamada de Emergência',
      call108: 'Ligar para 108 - Número Nacional de Emergência',
      callAmbulanceLocation: 'Chamar Ambulância + Localização',
      call108shareLocation: 'Ligue para o 108 e partilhe a sua localização automaticamente',
      nearbyHospitals: 'Hospitais Próximos',
      findHospitals: 'Encontrar hospitais e clínicas nas proximidades',
      nearbyPharmacy: 'Farmácia Próxima',
      findPharmacies: 'Encontrar farmácias perto da sua localização',
      share: 'Partilhar',
      shareLocation: 'Partilhar Localização',
      shareGps: 'Partilhar localização GPS com serviços de emergência',
      alertAllContacts: 'Alertar Todos os Contatos',
      sendSmsToContacts: 'Enviar SMS de emergência para todos os contatos',
      videoCallDoctor: 'Videochamada para Médico',
      startVideoConsult: 'Iniciar videoconsulta de emergência',
      doctorDirectory: 'Diretório de Médicos',
      contactDoctors: 'Contactar diretamente os médicos disponíveis',
      urgent: 'URGENTE',
      open: 'ABRIR',
      shareLocationPrompt: 'Partilhe a sua localização utilizando uma das opções abaixo ou copie o link.',
      copy: 'Copiar',
      copied: 'Copiado',
      close: 'Fechar',
      shareFile: 'Compartilhar Arquivo',
      shareFileNotSupported: 'Seu navegador não suporta o compartilhamento de arquivos diretamente. Por favor, baixe o documento para compartilhá-lo manualmente.',
      downloadFile: 'Baixar Arquivo',
      profile: 'Perfil',
      searchDoctors: 'Pesquisar médicos, hospitais...',
      call: 'Ligar',
      connecting: 'Conectando...',
      endCall: 'Terminar chamada',
    }
  };
  
  readonly translationsMap = computed(() => {
    const lang = this.currentLanguage();
    const baseLang = lang.split('-')[0];
    return this.translations[lang] 
        || this.translations[baseLang] 
        || this.translations['en'];
  });

  private translationQueue: { text: string; sourceLang: string; resolve: (value: string) => void; reject: (reason?: any) => void; }[] = [];
  private isProcessingQueue = false;

  setLanguage(lang: string): void {
    const baseLang = lang.split('-')[0];
    if (this.availableLanguages.some(l => l.code === baseLang)) {
      this.currentLanguage.set(baseLang);
    } else {
        this.currentLanguage.set('en');
    }
  }

  translate(key: string): string {
    return this.translationsMap()[key] || key;
  }

  translateText(text: string, sourceLang: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const targetLang = this.currentLanguage();
      const sourceBaseLang = sourceLang.split('-')[0];
      
      if (sourceBaseLang === targetLang) {
        resolve(text);
        return;
      }

      const cacheKey = `${sourceBaseLang}:${targetLang}:${text}`;
      const cached = this.translationCache()[cacheKey];
      if (cached) {
        resolve(cached);
        return;
      }

      this.translationQueue.push({ text, sourceLang: sourceBaseLang, resolve, reject });
      this.processTranslationQueue();
    });
  }

  private async processTranslationQueue(): Promise<void> {
    if (this.isProcessingQueue || this.translationQueue.length === 0) {
      return;
    }
    this.isProcessingQueue = true;

    const { text, sourceLang, resolve, reject } = this.translationQueue.shift()!;
    
    try {
      const targetLang = this.currentLanguage();
      const cacheKey = `${sourceLang}:${targetLang}:${text}`;
      
      const translatedText = await this.geminiService.translate(text, sourceLang, targetLang);
      
      this.translationCache.update(cache => ({
        ...cache,
        [cacheKey]: translatedText,
      }));
      resolve(translatedText);
    } catch (error) {
      console.error('Translation failed in queue:', error);
      reject(error);
    } finally {
        // Add a small delay to respect rate limits before processing the next item
        setTimeout(() => {
            this.isProcessingQueue = false;
            this.processTranslationQueue();
        }, 500); // 500ms delay between translation calls
    }
  }
}
